### ISSUE TITLE
compile error: pls resolve unresolved conflicts :)

### ISSUE THREAD

**Issue by skeletor-spaceman** [axiom-crypto/axiom-apps#1]
https://github.com/axiom-crypto/axiom-apps/blob/2d1d2125904411e83b992ef7c2d429f6aed49f84/rust-toolchain#L1
[uniswap-twap/Cargo.toml](https://github.com/axiom-crypto/axiom-apps/blob/2d1d2125904411e83b992ef7c2d429f6aed49f84/uniswap-twap/Cargo.toml#L20)

**Comment by jonathanpwang** [comment]
Hopefully fixed now in https://github.com/axiom-crypto/axiom-apps/commit/3e7e69f72244d45e9ec7c2eaa11d060bfa8f936a

**Comment by skeletor-spaceman** [comment]
awesome, ty!
